name: Jacob

markdown: kramdown
kramdown:
     input: GFM
     syntax_highlighter: rouge

# baseurl: /
# encoding: utf-8
# gems:
#   - jekyll-gist
# set :markdown_engine, :kramdown
# activate: rouge_syntax
